//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolment
    {
        public int EnrolmentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> DateOfEnrolment { get; set; }
        public Nullable<bool> TuitionPaid { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student student { get; set; }
    }
}
