//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        public int Id { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<decimal> PizzaPrice { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
